'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowRight, Check, Camera, ChevronDown, Leaf, Menu, Phone, X } from 'lucide-react'
import { areas, GALLERY, INSTAGRAM, LOGO, OWNER, PHONE, WHATSAPP } from '@/lib/site-data'
export { areas, GALLERY, INSTAGRAM, LOGO, OWNER, PHONE, WHATSAPP } from '@/lib/site-data'

const nav = [['Home','/'],['About us','/about-us'],['Our services','/our-services'],['Service areas','/service-areas'],['Grass gallery','/grass-gallery'],['Contact us','/contact-us'],['Owner details','/owner-details']]

export function Header() {
  const [open, setOpen] = useState(false)
  return <header className="site-header"><div className="container header-inner">
    <Link href="/" className="brand"><img src={LOGO} alt="SR Green Lawn logo" /><span><strong>SR Green Lawn</strong><small>Natural grass specialists</small></span></Link>
    <nav className={open ? 'nav open' : 'nav'}>{nav.map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)}>{label}</Link>)}<a className="nav-call" href={`tel:+${PHONE}`}><Phone size={16} /> Call now</a></nav>
    <button className="menu-button" aria-label="Toggle menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button>
  </div></header>
}

export function Footer() { return <footer><div className="container footer-grid"><div><Link href="/" className="brand footer-brand"><img src={LOGO} alt="SR Green Lawn logo" /><span><strong>SR Green Lawn</strong><small>Lush lawns. Healthy yards.</small></span></Link><p className="muted">Premium natural grass, lawn installation and landscape care for homes, farms, schools and commercial spaces.</p></div><div><h4>Explore</h4>{nav.slice(1,5).map(([l,h])=><Link key={h} href={h}>{l}</Link>)}</div><div><h4>Contact</h4><a href={`tel:+${PHONE}`}>+91 70119 03745</a><a href="mailto:srgreenlawn@gmail.com">srgreenlawn@gmail.com</a><span>Dasna, Ghaziabad, UP 201015</span></div></div><div className="container footer-bottom"><span>© 2026 SR Green Lawn. All rights reserved.</span><a href={INSTAGRAM}><Camera size={16}/> Instagram</a></div></footer> }

export function FloatingActions() { return <div className="floating-actions"><a className="float-call" href={`tel:+${PHONE}`} aria-label="Call SR Green Lawn"><Phone /></a><a className="float-wa" href={`https://wa.me/${WHATSAPP}?text=Hello%20SR%20Green%20Lawn%2C%20I%20need%20a%20lawn%20quote.`} aria-label="Chat on WhatsApp">WA</a></div> }

export function Shell({ children }: { children: React.ReactNode }) { return <><Header />{children}<FloatingActions /><Footer /></> }
export function SectionHeading({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="section-heading"><span className="eyebrow"><Leaf size={15}/>{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</div> }
export function CTA({ href='/contact-us', children='Get a free quote' }: { href?: string; children?: React.ReactNode }) { return <Link className="button button-primary" href={href}>{children}<ArrowRight size={17}/></Link> }
export function FeatureList({ items }: { items: string[] }) { return <ul className="feature-list">{items.map(i=><li key={i}><Check size={17}/>{i}</li>)}</ul> }
export function FAQ({ items }: { items: [string,string][] }) { return <div className="faq">{items.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div> }
export function PageHero({ eyebrow, title, text }: { eyebrow:string; title:string; text:string }) { return <section className="page-hero"><div className="container"><span className="eyebrow"><Leaf size={15}/>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></section> }
export function InquiryForm() { const [sent,setSent]=useState(false); return <form className="inquiry-form" onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent ? <div className="success"><Check size={32}/><h3>Thank you — your enquiry is received.</h3><p>We will call you shortly. For a faster response, message us on WhatsApp.</p><a className="button button-primary" href={`https://wa.me/${WHATSAPP}`}>Open WhatsApp</a></div> : <><div className="form-grid"><label>Full name<input required name="name" placeholder="Your name" /></label><label>Phone number<input required name="phone" type="tel" placeholder="10-digit mobile number" /></label><label>City / location<input required name="location" placeholder="e.g. Noida, Ghaziabad" /></label><label>Approx. area<select name="area" defaultValue=""><option value="" disabled>Select area size</option><option>Up to 500 sq ft</option><option>500–1500 sq ft</option><option>1500–3000 sq ft</option><option>3000+ sq ft</option></select></label></div><label>Tell us about your lawn project<textarea required name="message" rows={4} placeholder="New lawn, replacement, maintenance or landscaping..." /></label><button className="button button-primary" type="submit">Send enquiry <ArrowRight size={17}/></button></>}</form> }
export function GalleryGrid({ limit }: { limit?: number }) { return <div className="gallery-grid">{GALLERY.slice(0,limit).map(([title,src])=><figure key={src}><img src={src} alt={title} loading="lazy"/><figcaption><span>{title}</span><ArrowRight size={17}/></figcaption></figure>)}</div> }

export const keywords = ['natural grass','green grass','lawn grass','grass carpet','lawn installation','landscaping near me','garden landscaping','lawn contractor Delhi NCR','natural grass Noida','lawn grass Ghaziabad','grass carpet Noida','lawn installation Greater Noida','garden grass Hapur','landscape designer Agra','grass supplier Jaipur','natural turf Uttar Pradesh','lawn maintenance Rajasthan','garden contractor Punjab','sports turf Haryana','grass rolls Chandigarh','lawn service Jammu Kashmir','residential lawn','commercial lawn','farmhouse landscaping','villa lawn design','terrace garden grass','backyard lawn','front lawn installation','office landscaping','school playground grass','resort lawn','park grass installation','corporate garden','wedding lawn setup','event grass rental','pet friendly lawn','low maintenance grass','shade tolerant grass','summer lawn care','winter lawn care','monsoon lawn care','fresh turf rolls','instant lawn','ready grass carpet','quality turf grass','budget lawn installation','premium lawn service','lawn leveling','soil preparation','grass laying service','grass cutting service','garden makeover','lawn repair','lawn replacement','irrigation setup','sprinkler installation','drainage for lawn','edging and borders','plantation service','hedge trimming','garden cleaning','landscape maintenance','organic lawn care','fertilizer lawn care','weed control lawn','pesticide free lawn','natural garden design','green garden contractor','best lawn grass near me','grass delivery Delhi','turf delivery Noida','grass delivery Ghaziabad','lawn experts NCR','professional landscaper Delhi','landscape company Noida','trusted lawn contractor','affordable turf installation','lawn quote near me','garden renovation','new lawn service','old lawn replacement','durable natural grass','soft lawn grass','dense green turf','fresh green carpet','outdoor landscaping','residential landscaping','commercial landscaping','institutional landscaping','farm lawn','nursery grass supply','grass for cricket ground','grass for football ground','play area grass','walkway landscaping','courtyard lawn','rooftop lawn','balcony garden','entrance landscaping','nature friendly garden','sustainable lawn','water efficient lawn','lawn consultation','site visit lawn','same day lawn quote','SR Green Lawn','Manish Prajapati lawn service','Dasna grass supplier','Ghaziabad natural grass','Delhi NCR turf service','UP lawn specialist']
